version: 2
updates:
- package-ecosystem: gradle
  directory: "/finish"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
- package-ecosystem: gradle
  directory: "/start"
  schedule:
    interval: monthly
  open-pull-requests-limit: 50
